// <auto-generated />
using AplikacjaLataPrzestepne.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AplikacjaLataPrzestepne.Migrations
{
    [DbContext(typeof(Wyszukiwania))]
    partial class WyszukiwaniaModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AplikacjaLataPrzestepne.Forms.RokPrzestepny", b =>
                {
                    b.Property<int>("Rok")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Rok"), 1L, 1);

                    b.Property<string>("Imie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("czy_przestepny")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Rok");

                    b.ToTable("DanePrzestepne");
                });
#pragma warning restore 612, 618
        }
    }
}
